version: "3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
    - .:/home/node/app
    - /home/node/app/node_modules
    ports:
    - 80:3333
    depends_on:
      - db
  db:
    image: mariadb
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DB_NAME}
    #volumes:
      #- ./.docker/mysql:/var/lib/mysql
    ports:
      - 3306:3306